version: '3.8'

services:
  # --- CONTAINER APPLICATION (NODE.JS) ---
  app:
    build: .
    container_name: sipmas_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    depends_on:
      db:
        condition: service_healthy # Aplikasi baru berjalan jika DB sudah benar-benar siap

  # --- CONTAINER DATABASE (MYSQL 8.0) ---
  db:
    image: mysql:8.0
    container_name: sipmas_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
      # OTOMATISASI: Mengimpor file SQL saat database pertama kali dibuat
      - ./db_sipmas.sql:/docker-entrypoint-initdb.d/db_sipmas.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: